# SPDX-License-Identifier: AGPL-3.0-or-later

- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  #- Amber kil by upstream we still have ours but it testfails oh well.
  - Bagel
  - Box
  - Cluster
  #- Core
  - Fland
  #- Loop Goobstation - I love maintenance!!!
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach # Omu?
  #- Train # Goobstation - all my friends hate train
  - FlandHighPop
  - OasisHighPop
# - Barratry # Omu - Trimming map pool.
  - Kettle # Goobstation - Re-add kettle (before it was gemini!)
  - Leonid # Goobstation - for goob by goob
  - Delta # Goobstation - ported from Corvax
  #- Chloris # Goobstation - also Corvax because we love goidamaps # Omu, derotate this map.
  - Cog # those who forget to clear their multitool
  # - Serpentcrest # Goobstation when contra # Omu no
  #- Plasma # Goob - No. Leave it to the mappers.
  #- Reach
  #- Exo # Goobstation - Just no
  #- Snowball #omu
  - Glacier #OMU!!!!

