# SPDX-License-Identifier: AGPL-3.0-or-later
#Misc outfit startingGear definitions.

#Skeleton Biker - Just a skeleton now
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes

# Syndicate Operative Outfit - Civilian
- type: startingGear
  id: SyndicateOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlack
    id: SyndiPDA
#    ears: ClothingHeadsetAltSyndicate # Omu

# Syndicate Footsoldier Gear - No Headset
- type: startingGear
  id: SyndicateFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  inhand:
  - WeaponPistolViper # Goobstation - no fistfighting
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  parent: SyndicateOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    eyes: ClothingEyesHudSyndicate
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombatFilled
    ears: ClothingHeadsetAltSyndicate # Omu
  storage:
    back:
    - BoxSurvivalSyndicate

- type: startingGear
  id: SyndicateFootsoldierTeamLeaderGear
  parent: SyndicateFootsoldierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    head: ClothingHeadHatOutlawHat
    outerClothing: ClothingOuterArmorBasicSlim
    back: ClothingBackpackSatchel
    pocket1: BaseUplinkRadio125TC
    pocket2: EnergySword

# Nanotrasen Paramilitary Unit Gear
- type: startingGear
  id: NanotrasenParamilitaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSlotsSecurity # Goobstation - Slots Based Survival Boxes
    - Flash
    - MagazinePistol

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue

- type: startingGear
  id: MobMonkeyGear
  equipment:
    head: ClothingHeadHatTophat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    id: PunPunIDCard

- type: startingGear
  id: MobPollyGear
  equipment:
    ears: ClothingHeadsetEngineering

# Emotional Support Scurret

- type: startingGear
  id: EmotionalSupportScurretGear
  equipment:
    id: ScurretPDA

# DeathMatch Gear

- type: startingGear
  id: DeathMatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
  inhand:
    - WeaponMeleeToolboxRobust

#Brigmedic | Omu - CORPSMAN!!

- type: startingGear
  id: BrigmedicGear
#  equipment: # Omu, so its all moved to the loadout....
#    eyes: ClothingEyesGlassesMedSec #Omu - Available in loadouts
#    id: BrigmedicPDA # Omu, corpsman got 4 freaking pdas now idk why
#    ears: ClothingHeadsetBrigmedic # EE parity like i was told to do ///Omu - Available in loadouts
#    belt: ClothingBeltMedicalEMTFilled #Omu - Available in loadouts
#    pocket1: OfficerGunCase # Omu, item is in loadouts instead``
#    pocket2: WeaponDisabler # Goob ///Omu - Disabler is part of corpsman's belt fill
  storage:
    back:
    - Flash
    - ClothingMaskBreathMedicalSecurity
    - MedkitCombatFilled #Omu

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelAdmin
    id: AdminPDA
  storage:
    back:
    - GasAnalyzer
    - trayScanner
    - AccessConfiguratorUniversal
    - Multitool
    - WelderExperimental # Omu Edit - More Admin Tools
    - PowerDrill # Omu Edit - More Admin Tools
    - GeigerCounter # Omu Edit - More Admin Tools
    - JawsOfLife # Omu Edit - More Admin Tools

#Gladiator with spear
- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult

#Ash Walker
- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult

#Banana Clown
- type: startingGear
  id: BananaClown
  equipment:
    id: VisitorPDA
    back: ClothingBackpackClown
    shoes: ClothingShoesClownBanana
    jumpsuit: ClothingUniformJumpsuitClownBanana
    mask: ClothingMaskClownBanana
    pocket1: BikeHorn
    pocket2: ClownRecorder

# Passenger but without the ID, bag, or headset
- type: startingGear
  id: LimitedPassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
